name: phase_space_reconstruction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - h5py
  - scipy
  - scikit-image
  - matplotlib
  - tqdm
  - ipython
  - ipykernel
  - distgen=0.6.12
  - pip
  - pip:
    # - git+https://github.com/bmad-sim/Bmad-X
      - torchensemble==0.1.7
      - pyro-ppl
      - blitz-bayesian-pytorch

