name: ps-reconstruction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - tqdm
  - distgen=0.6.12
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torchensemble==0.1.7
    - pyro-ppl
    - blitz-bayesian-pytorch

