name: gpsr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - lightning
  - python>=3.10
  - ipython
  - ipykernel
  - pytorch
  - pytorch-cuda>=11.8
  - tensorboard
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - pip
  - pip:
    - cheetah-accelerator
