n_particle: 100_000
total_charge:
  units: nC
  value: 10
start:
  type: time
random_type: pseudo
r_dist:
  sigma_xy:
    units: mm
    value: 3
  type: radial_gaussian
px_dist:
  sigma_px:
    units: MeV/c
    value: 0.00434
  type: gaussian
py_dist:
  sigma_py:
    units: MeV/c
    value: 0.00434
  type: gaussian
z_dist:
  avg_z:
    units: mm
    value: 0
  sigma_z:
    units: mm
    value: 1
  type: gaussian
pz_dist:
  avg_pz:
    units: MeV/c
    value: 43.4
  sigma_pz:
    units: MeV/c
    value: 0.00434
  type: gaussian