name: Test build and publish to TestPyPI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/gpsr
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install build
        run: python -m pip install build  --user

      - name: Create the distribution
        run: |
          git fetch --prune --unshallow --tags
          python -m build

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
